name: Release Drafter

on:
  pull_request:
    types: [closed]

jobs:
  draft:
    uses: edalzell/github-workflows/.github/workflows/release-draft.yml@f6f95441899dd87addad89818061ce0100b22862 # v1.1.0
    permissions:
      contents: write
      pull-requests: write
