name: Release Drafter

on:
  pull_request:
    types: [closed]

jobs:
  draft:
    uses: edalzell/github-workflows/.github/workflows/release-draft.yml@2bcb000b0c2aba1e5f15e2d5d86a26be4f89cd83 # v1.1.1
    permissions:
      contents: write
      pull-requests: write
