name: Release Publish

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    if: >-
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'release')
    uses: edalzell/github-workflows/.github/workflows/release-publish.yml@d3446ce832a9191e54e4015c91e2912f930f0df1 # v1.0.0
    permissions:
      contents: write
