name: Release Prepare

on:
  workflow_dispatch:

jobs:
  prepare:
    uses: edalzell/github-workflows/.github/workflows/release-prepare.yml@eb649b567a33522b9098823ab130d4405f6e7041 # v1
    permissions:
      contents: write
      pull-requests: write
