name: Release Prepare

on:
  workflow_dispatch:

jobs:
  prepare:
    uses: edalzell/github-workflows/.github/workflows/release-prepare.yml@2bcb000b0c2aba1e5f15e2d5d86a26be4f89cd83 # v1.1.1
    permissions:
      contents: write
    secrets:
      release_token: ${{ secrets.RELEASE_TOKEN }}
